### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by davidclevenger** [JonnyPtn/SFML-DOOM#9]
Hi,

I'm having trouble building on Ubuntu 18.04 64-bit. 

Error log below.

$ cmake .
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "FindSFML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SFML", but
  CMake did not find one.

  Could not find a package configuration file provided by "SFML" with any of
  the following names:

    SFMLConfig.cmake
    sfml-config.cmake

  Add the installation prefix of "SFML" to CMAKE_PREFIX_PATH or set
  "SFML_DIR" to a directory containing one of the above files.  If "SFML"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by JonnyPtn** [comment]
My best guess is you have a version of sfml less than 2.5 installed. I should probably specify that as a requirement now

Let me know if updating sfml to 2.5 helps?

**Comment by davidclevenger** [comment]
Will do

**Comment by davidclevenger** [comment]
Updated to 2.5. That fixed the original issue. Sources build fine but now just having a linker issue.

<img width="579" alt="screen shot 2019-02-20 at 2 00 23 pm" src="https://user-images.githubusercontent.com/24283448/53117033-fc9a4780-3517-11e9-8aff-057f62af0add.png">

As a note, the .dmg asset will run fine.

**Comment by JonnyPtn** [comment]
Interesting, Are you linking statically by any chance? Might be a mac lib missing from the linker commands

Also try using the Xcode cmake generator (looks like you're using the default unix makefiles one?)

**Comment by davidclevenger** [comment]
I beleive I am. I am not familiar with the Xcode cmake generator. I will try building on my linux partition and see if I have the same errors.

**Comment by JonnyPtn** [comment]
It should be fine on Linux because those unresolved externals are from the macOS libs

To use the Xcode generator with cmake just pass -GXcode to the cmake command
